### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by mgochoa** [guilhermewaess/SemVue#10]
Do you need any help pal?

**Comment by arthurtyukayev** [comment]
There hasn't been an update to this repo in a while. 

https://semantic-ui-vue.github.io/

You can check that, it might be more up to date.

**Comment by mgochoa** [comment]
I'm checking out. Thanks.

**Comment by guilhermewaess** [comment]
Unfortunately, I stopped to work on the project which demands the evolution of SemVue.
My focus right now is move to Europe, so, the time is tight, but if you need any new component which isn't implemented yet, let me know, and I'll try to implement soon as possible :D

In time, I didn't know the project that @arthurtyukayev recommended, looks good.
Thanks for share @arthurtyukayev

**Comment by arthurtyukayev** [comment]
No problem.
